import type { DadosDoLancamentoFinanceiro, LancamentoFinanceiro } from '@/dominio/lancamento-financeiro';
import { gravarBancoLocal, lerBancoLocal } from '@/infraestrutura/banco/arquivo-local';
import { conexaoPostgres } from '@/infraestrutura/banco/conexao';

function paraLancamento(linha: Record<string, any>): LancamentoFinanceiro { return { id: linha.id, tipo: linha.tipo, descricao: linha.descricao, categoria: linha.categoria, valor: Number(linha.valor), dataDeVencimento: linha.data_vencimento.toISOString(), dataDePagamento: linha.data_pagamento?.toISOString() ?? null, situacao: linha.situacao, reservaId: linha.reserva_id ?? null, observacoes: linha.observacoes, criadoEm: linha.criado_em.toISOString() }; }
export async function listarLancamentosFinanceiros(): Promise<LancamentoFinanceiro[]> { const sql = conexaoPostgres(); if (!sql) return (await lerBancoLocal()).lancamentosFinanceiros; try { return (await sql`select * from lancamentos_financeiros order by data_vencimento desc`).map(paraLancamento); } finally { await sql.end(); } }
export async function cadastrarLancamentoFinanceiro(dados: DadosDoLancamentoFinanceiro): Promise<LancamentoFinanceiro> { const sql = conexaoPostgres(); const id = crypto.randomUUID(); if (!sql) { const banco = await lerBancoLocal(); const item: LancamentoFinanceiro = { id, ...dados, dataDeVencimento: dados.dataDeVencimento.toISOString(), dataDePagamento: dados.dataDePagamento?.toISOString() ?? null, criadoEm: new Date().toISOString() }; banco.lancamentosFinanceiros.push(item); await gravarBancoLocal(banco); return item; } try { const [linha] = await sql`insert into lancamentos_financeiros (id,tipo,descricao,categoria,valor,data_vencimento,data_pagamento,situacao,reserva_id,observacoes) values (${id},${dados.tipo},${dados.descricao},${dados.categoria},${dados.valor},${dados.dataDeVencimento},${dados.dataDePagamento},${dados.situacao},${dados.reservaId},${dados.observacoes}) returning *`; return paraLancamento(linha); } finally { await sql.end(); } }
export async function atualizarLancamentoFinanceiro(id: string, dados: DadosDoLancamentoFinanceiro): Promise<LancamentoFinanceiro> { const sql = conexaoPostgres(); if (!sql) { const banco = await lerBancoLocal(); const indice = banco.lancamentosFinanceiros.findIndex((item) => item.id === id); if (indice < 0) throw new Error('LANCAMENTO_NAO_ENCONTRADO'); const item: LancamentoFinanceiro = { ...banco.lancamentosFinanceiros[indice], ...dados, dataDeVencimento: dados.dataDeVencimento.toISOString(), dataDePagamento: dados.dataDePagamento?.toISOString() ?? null }; banco.lancamentosFinanceiros[indice] = item; await gravarBancoLocal(banco); return item; } try { const [linha] = await sql`update lancamentos_financeiros set tipo=${dados.tipo},descricao=${dados.descricao},categoria=${dados.categoria},valor=${dados.valor},data_vencimento=${dados.dataDeVencimento},data_pagamento=${dados.dataDePagamento},situacao=${dados.situacao},reserva_id=${dados.reservaId},observacoes=${dados.observacoes} where id=${id} returning *`; if (!linha) throw new Error('LANCAMENTO_NAO_ENCONTRADO'); return paraLancamento(linha); } finally { await sql.end(); } }
export async function excluirLancamentoFinanceiro(id: string): Promise<void> { const sql = conexaoPostgres(); if (!sql) { const banco = await lerBancoLocal(); const tamanho = banco.lancamentosFinanceiros.length; banco.lancamentosFinanceiros = banco.lancamentosFinanceiros.filter((item) => item.id !== id); if (banco.lancamentosFinanceiros.length === tamanho) throw new Error('LANCAMENTO_NAO_ENCONTRADO'); await gravarBancoLocal(banco); return; } try { const removidos = await sql`delete from lancamentos_financeiros where id=${id} returning id`; if (!removidos.length) throw new Error('LANCAMENTO_NAO_ENCONTRADO'); } finally { await sql.end(); } }

